import './globals.css';

export const metadata = {
  title: 'Rank do Concurseiro',
  description: 'Generated by Next.js',
  appleWebApp: { statusBarStyle: "black-translucent" }
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  )
}
